name: Code Review with Grok
on:
  pull_request:
    types: [opened, synchronize]
permissions:
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Grok Review and Comment
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

          DIFF=$(gh pr diff ${{ github.event.pull_request.number }})
          SAFE_CONTENT=$(jq -Rn --arg text "$DIFF" '{"model": "grok-3-mini-beta", "messages": [{"role": "user", "content": $text}]}')

          RESPONSE=$(curl -s -X POST https://api.x.ai/v1/chat/completions \
            -H "Authorization: Bearer ${{ secrets.GROK_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d "$SAFE_CONTENT")

          echo "$RESPONSE"
          gh pr comment ${{ github.event.pull_request.number }} --body "$RESPONSE"
